<!-- jquery cdn -->
    
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js"></script> 
    <!-- 
    <link rel="stylesheet" href="./jqueryMobile/jquery.mobile-1.4.5/jquery.mobile-1.4.5.css" />
    <script src="./jquery/jquery-1.11.0.js"></script>
    <script src="./jqueryMobile/jquery.mobile-1.4.5/jquery.mobile-1.4.5.js"></script> -->